# -*- coding: utf-8 -*-
"""Pothole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMVHoz3CiMLNRvd1rvs3EetVB8Rqz_rM
"""

from keras.models import Model
import cv2
import math

#converting video to image
count = 0
videoFile = "/content/drive/MyDrive/Final Year Project/output_Road.avi"
cap = cv2.VideoCapture(videoFile)   # capturing the video from the given path
frameRate = cap.get(5) #frame rate
x=1
while(cap.isOpened()):
    frameId = cap.get(1) #current frame number
    ret, frame = cap.read()
    if (ret != True):
        break
    if (frameId % math.floor(frameRate) == 0):
        filename ="/content/sample_data/potholes/frame%d.jpg" % count;count+=1
        cv2.imwrite(filename, frame)
cap.release()
print ("Done!")

from tensorflow import keras
model=keras.models.load_model('/content/drive/MyDrive/Final Year Project/model_1.h5')

imagepaths=[]
import os
for dirname, _, filenames in os.walk('/content/sample_data/potholes'):
    for filename in filenames:
        path = os.path.join(dirname, filename)
        imagepaths.append(path)

print(len(imagepaths))

import numpy as np
IMG_SIZE=256
X=[]
for image in imagepaths:
    try:
        img1 = cv2.imread(image,cv2.IMREAD_COLOR)
        img = cv2.resize(img1, (IMG_SIZE,IMG_SIZE))
        X.append(np.array(img))
    except:
        pass
print(len(X))

X=np.array(X)
prediction=model.predict([X])
print(prediction)

y_pred = np.argmax(prediction, axis=1)
print(y_pred)

path="/content/sample_data/potholes"
files = os.listdir(path)
files

from tqdm import tqdm
import matplotlib.pyplot as plt

for i in tqdm(files):
    pth = os.path.join(path,i)
    X = cv2.imread(pth,cv2.IMREAD_COLOR)
    X = cv2.resize(X,(256,256))
    plt.figure()
    plt.imshow(X[:,:,::-1]) 
    plt.show()  

    X = np.array(X)
    X = np.expand_dims(X, axis=0)

    y_pred = np.round(model.predict([X]))
    if y_pred[0][0] == 1:
        print("Plain Road")
    else:
        print("Pothole Road")

